spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://127.0.0.1:5432/postgres
  redis:
    host: 127.0.0.1
    password:
    port: 6379
